# Generated by Django 3.2.5 on 2021-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0004_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
