# Generated by Django 3.2.5 on 2021-08-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0006_auto_20210815_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
