# Generated by Django 3.2.5 on 2021-09-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0010_auto_20210915_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
