# Generated by Django 3.2.5 on 2021-09-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0013_auto_20210915_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
