# Generated by Django 3.2.5 on 2021-09-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0015_auto_20210915_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='slug',
            new_name='slugF',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='slugF',
        ),
    ]
