# Generated by Django 3.2.5 on 2021-09-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0016_auto_20210915_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='slugF',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slugF',
        ),
    ]
